### ISSUE TITLE
Syntax error no javascript

### ISSUE THREAD

**Issue by andrechalom** [merepresenta/merepresenta#1]
https://github.com/merepresenta/merepresenta/blob/6441e3c39396050317c0919a9557f64e6b085770/interno/scripts/BuscaDados.js#L18

Essa é a versão mais atual do código? Por favor verifique!

**Comment by luizalbsilva** [comment]
Já revisto no commit 9e0d6b34a92dd9295391088e01271f2e20d1c8fa
