### ISSUE TITLE
Paginação de resultados?

### ISSUE THREAD

**Issue by andrechalom** [merepresenta/merepresenta#10]
O código atual da API (arquivo "merepresenta.php") possui provisões para retornar um conjunto paginado de dados. No entanto, o JavaScript sempre força "limites: {primeiro: 1, ultimo: 10}". É necessário que os usuários possam navegar essa lista inteira, e não os primeiros 10 resultados.

**Comment by luizalbsilva** [comment]
Já revisto no commit 9e0d6b34a92dd9295391088e01271f2e20d1c8fa
