### ISSUE TITLE
O campo "cidade" terá um suggest?

### ISSUE THREAD

**Issue by andrechalom** [merepresenta/merepresenta#12]
Na plataforma 2016, o campo de Cidade gerava um elemento de autocomplete / autosuggest. Isso vai ser implementado nessa plataforma?

**Comment by luizalbsilva** [comment]
Podemos fazer um autocomplete sim. Inicialmente eu achei que seria uma pesquisa estilo "contém".

**Comment by andrechalom** [comment]
Poderia ser um campo de "contém", mas pela estrutura da pesquisa isso me parece esquisito. Em que caso eu precisaria fazer uma pesquisa de candidatos de "cidades que começam com 'Rio de'"?

**Comment by luizalbsilva** [comment]
Podemos fazer o contém então. Vamos deixar essa issue por último? Mas já pode ser precisar assim na view

**Comment by andrechalom** [comment]
Não entendi sua resposta. Mas podemos deixar esse campo como "contém" por enquanto, acho que esse não é um issue crítico para a entrega inicial.
