### ISSUE TITLE
Mudar o slug das páginas

### ISSUE THREAD

**Issue by andrechalom** [merepresenta/merepresenta#17]
- [x] A página "query-politician" deve ser renomeada para "representou". 

- [x] A página "show-politician" deve ser renomeada para "candidato"? Verificar no Slack

**Comment by luizalbsilva** [comment]
Aguardando apenas a definição da alteração do "show-politician".. O outro foi alterado no commit 
d9dcacd1fa29c40a973dc836c3b443a747e7aa65

**Comment by luizalbsilva** [comment]
show-politician alterando no commit 5e650060c7aace5dba62f339ea6ae3a6ef0d3a13
