### ISSUE TITLE
Incluir scripts de importação de dados

### ISSUE THREAD

**Issue by andrechalom** [merepresenta/merepresenta#2]
Ver discussão no Slack. Acredito que os scripts de importação devam estar versionados, em parte porque eles vão precisar ser alterados com os campos que precisam ser buscados nas tabelas do TSE.

**Comment by luizalbsilva** [comment]
Cópia do banco disponível em http://www.tamanhofamilia.com.br/tse.zip (106,6mb)
Scripts disponível em d03e110099ded1434aecc80136535d320ede49c3
