### ISSUE TITLE
Página inicial está em branco

### ISSUE THREAD

**Issue by luizalbsilva** [merepresenta/merepresenta#22]
Verificar dados colocados no repositório e banco.

**Comment by andrechalom** [comment]
A página inicial está sendo gerenciada pelo tema "Integral". Quando eu desabilito a "página estática" do Integral, ele mostra uma página corretamente, mas quando eu habilito, ele não mostra nada. Vou investigar.

**Comment by andrechalom** [comment]
Entendi o problema. O Integral precisa dos plugins "redux-framework" e "contact-form-7" para funcionar. Vou incluir ambos no nosso código fonte.
