### ISSUE TITLE
Biblioteca de mídia é perdida no deploy?

### ISSUE THREAD

**Issue by andrechalom** [merepresenta/merepresenta#25]
O diretório /wp-content/uploads é perdido quando ocorre deploy, precisamos configurar os uploads para acessarem uma área de storage permanente.

**Comment by andrechalom** [comment]
Estou movendo as imagens usadas no layout para o diretório do tema, então esse issue tem prioridade baixa. Mas isso vai ser uma questão no futuro, para permitir que o restante do time possa criar posts com imagens, etc.

**Comment by luizalbsilva** [comment]
O armazenamento das imagens é feita na pasta /app/wp-content
Configurei o dokku para gravar o conteúdo dessa pasta para /home/ubuntu/wp-upload

Passará a ser gravada a partido do próximo deploy ou rebuild da aplicação. (Há material para fazer deploy)

**Comment by andrechalom** [comment]
Tem um pequeno problema: o tema está na pasta /wp-content. E ele precisa estar versionado.
