### ISSUE TITLE
Link permanente de "show-politician"

### ISSUE THREAD

**Issue by andrechalom** [merepresenta/merepresenta#26]
O link da página de "politicos" reverteu para "show-politician" durante o deploy. Precisamos fazer com que isso não aconteça mais.

**Comment by andrechalom** [comment]
~~Ainda: a página de detalhe de político não está aparecendo~~
[EDIT: isso deve ter sido problema de cache]

**Comment by andrechalom** [comment]
Realizei novo deploy, e o link não foi alterado. Vou manter o issue aberto até termos confirmação do que está acontecendo.

**Comment by luizalbsilva** [comment]
Quem coordena os links é o wordpress, através dos dados em banco. Nosso código apenas coordena a resposta, redirecionando '/politicos' ou '/representou' para nosso conteúdo.

Ver: /wp-conten/themes/integral/page.php, linhas 13-24
