### ISSUE TITLE
Configurar envio de e-mail

### ISSUE THREAD

**Issue by andrechalom** [merepresenta/merepresenta#27]
Criei um formulário de contato (acessível sob o link Contact na barra lateral do wp-admin), que está sendo servido na página principal do site. No entanto, o envio de e-mail não parece estar funcionando. É necessário configurar algo no servidor / na conta do hosting?

**Comment by luizalbsilva** [comment]
Acho que vai precisar do plugin wp-mail-smtp para configuração do SMTP do email 

https://br.wordpress.org/plugins/wp-mail-smtp/

**Comment by luizalbsilva** [comment]
O dokku não vem com o sendmail instalado.. assim sendo, o ideal é usarmos um plugin para utilizarmos SMTP ao invés do sendmail... Um exemplo é o wp-mail-smtp

https://br.wordpress.org/plugins/wp-mail-smtp/

**Comment by andrechalom** [comment]
Isso está

**Comment by luizalbsilva** [comment]
Conforme descrito no dia 15/11, 10hrs, configurei o SMTP com uma conta criada no mailjet.com. Essa conta é gratuita e é limitada a 200 envios por dia. Caso se façam necessarios mais envios, devemos fazer um upgrade no plano ou selecionar um outro fornecedor de SMTP. Existem diversos no mercado, inclusive podemos usar serviços da google ou yahoo. Se for esse o caso, por favor me envie os dados para configuração ou alterem em configurações->WP Mail SMTP
