### ISSUE TITLE
Scripts de importação devem incluir dados do TSE

### ISSUE THREAD

**Issue by andrechalom** [merepresenta/merepresenta#3]
Vide #2. Os scripts devem incluir um cruzamento com as bases de dados do TSE, disponíveis aqui: http://www.tse.jus.br/eleicoes/estatisticas/repositorio-de-dados-eleitorais

É necessário baixar dois conjuntos de dados dessa base, um com os Candidatos (para incluir cor, sexo, etc) e um segundo com Resultados (para incluir votação). Veja a modelagem de dados disponibilizada dia 07 de setembro

**Comment by luizalbsilva** [comment]
Cópia do banco disponível em http://www.tamanhofamilia.com.br/tse.zip (106,6mb)
Scripts disponível em d03e110099ded1434aecc80136535d320ede49c3
