### ISSUE TITLE
Importação de "respostas" deve desconsiderar os candidatos que não finalizaram o questionário

### ISSUE THREAD

**Issue by andrechalom** [merepresenta/merepresenta#6]
Da exata forma como isso foi feito em 2016, um candidato que não terminou o questionário não era mostrado pela plataforma antiga. Porque ele seria mostrado agora?

Isso pode ser feito na importação de dados ou na visualização, mas é preferível fazer na importação.

**Comment by luizalbsilva** [comment]
Boa ! O número de candidatos caiu bastante (913). Estou aproveitando para realizar uma série de checagens em conjunto com o que me pediu no slack

**Comment by luizalbsilva** [comment]
Inclui no commit d03e110099ded1434aecc80136535d320ede49c3
