### ISSUE TITLE
A tabela de candidatos deve incluir links para uma página com detalhes sobre o candidato

### ISSUE THREAD

**Issue by andrechalom** [merepresenta/merepresenta#7]
Isso está na especificação inicial do projeto. Porque ainda não foi feito?

**Comment by luizalbsilva** [comment]
Tabela em banco de dados? Se for, não está na diagramação, o que leva  a crer que será criada on-the-fly durante a apresentação. Aliás, isso vela a um outro  questionamento: O mesmo link deverá ser acrescido no arquivo CSV que poderá ser baixado?

**Comment by andrechalom** [comment]
Vide e-mail enviado em 18 de agosto:

> Precisamos essencialmente de duas telas funcionando.
> Tela 01: filtros de busca, visualização dos resultados como tabela, botão pra baixar os dados como csv. Quando o usuário clica no nome de um candidato, ele é direcionado para a tela 02.
> Tela 02: detalhes de cada candidato, foto, minibio, respostas, essencialmente os mesmos dados da tela 01, mas com uma apresentação mais bonitinha. Igual a tela existente hoje em http://vereadores.merepresenta.org.br/candidates/527

Não vi essa tela implementada ainda. A tabela que é gerada pelo filtro deveria ter uma coluna com um "clique aqui para ver detalhes". O link não precisa estar no csv.

**Comment by luizalbsilva** [comment]
a tela em questão será editável através do wordpress, ou terá seu visual fixo, exatamente como o do link?

**Comment by andrechalom** [comment]
A tela do filtro será uma Page do wordpress, não é mesmo? Imagino que a tela de detalhes de candidatos possa ser criada como uma Page que recebe o id do candidato e acessa o banco de dados para ser construida.

**Comment by luizalbsilva** [comment]
Já revisto no commit 9e0d6b34a92dd9295391088e01271f2e20d1c8fa
