### ISSUE TITLE
Data de nascimento

### ISSUE THREAD

**Issue by andrechalom** [merepresenta/merepresenta#8]
É melhor deixar datas de nascimento em branco como "NULL", ao invés de 1500. Colocar uma data em 1500 ferra tudo quando precisamos fazer pesquisas agregadas, p ex, calcular a idade média dos candidatos.

**Comment by luizalbsilva** [comment]
Foi realizado assim devido à modelagem do dados entregue. Vou alterar os scripts de criação do banco e importação.

**Comment by andrechalom** [comment]
Ao invés disso, veja se não é possível preencher todas as entradas com
dados reais.

Existe algum caso no qual os dados do TSE não tem a data de nascimento?

**Comment by luizalbsilva** [comment]
O vereador preencheu esse dado na eleição passada. Vou até verificar se existe esse campo hoje vazio, não verifiquei depois que retiramos da importação os registros que não finalizaram o questionário.

**Comment by andrechalom** [comment]
Sim, mas se o vereador não preencheu, use o dado do TSE ao invés da descoberta do Brasil

**Comment by luizalbsilva** [comment]
Foi dado obrigatório, estão todos preenchidos.
