### ISSUE TITLE
Implantação de filtros

### ISSUE THREAD

**Issue by andrechalom** [merepresenta/merepresenta#9]
Segundo e-mail 13 de julho de 2017 17:45, gui mohallem, filtros necessários são:

- [x] Estado
- [x] Cidade
- [x] Partidos
- [x] Pautas
- [x] Cor
- [x] Gênero (autodeclarado; com fallback para gênero TSE caso não haja informação)
- [ ] LGBT (desabilitado agoram as preparar prevendo plataforma de 2018

Além desses, o código atual indica que vc está implementando
- [ ] Situação candidatura
- [ ] Situação eleitoral
- [ ] Nota do partido (range)

Preenchi os boxes dos filtros que já estão funcionais hj, por favor atualize.

**Comment by andrechalom** [comment]
O filtro de nota do partido está funcionando caso o usuário preencha o mínimo e o máximo, mas se o usuário preenche apenas uma das duas, o resultado não é filtrado.

**Comment by luizalbsilva** [comment]
1. O que são pautas?
2. O filtro vou forçar o valor 0 no minimo ou 10 no máximo caso não esteja preenchido.
3. Demais campos (cor e generno) vou pegar do tse -- se não me engano não pegamos no sistema passado, por isso não coloquei. Eles serão por checkbox?
4. Os campos de situação da candidatura e eleitoral eu coloquei para ver como ficavam, iria confirmar antes de implementar.

**Comment by andrechalom** [comment]
1. Pautas, no momento, são as 14 perguntas cadastradas.
2. A escala de nota dos partidos vai de 0 a 10 ou de 0 a 100? Acho bom colocar isso explicitamente na view, talvez forçar o input máximo ser 10 caso essa seja a nota máxima.
3. Podem ser por checkbox, sim.
4. Situação eleitoral eu achei uma ótima ideia, é um filtro importante. Situação de candidatura não me parece importante agora.

**Comment by andrechalom** [comment]
Obs importante! O filtro das 14 perguntas deve ser feito de forma que é possível procurar candidatos que são FAVORÁVEIS às pautas. NÃO deve haver possibilidade de procurar candidatos CONTRÁRIOS ás pautas.

**Comment by luizalbsilva** [comment]
Os campos pedidos no email estão previstos no commit 9e0d6b34a92dd9295391088e01271f2e20d1c8fa
